COMMON_HEADER=${1}
TEMPLATE_CMAKELISTS_MAIN=${2}
TO_PROJECT_DIRECTORY=${3}

#   引入头文件
source  ${COMMON_HEADER}

#   拷贝CMakeLists.txt模板到主目录下
cd	${TO_PROJECT_DIRECTORY}
InstTmpltFile   ${CMAKELISTS} ${ARGUMENTS} ${TEMPLATE_CMAKELISTS_MAIN}
